### ISSUE TITLE
Incompatible with SwiftAC 

### ISSUE THREAD

**Issue by poluxtobee** [Metastruct/outfitter#48] opened 2019-12-26 19:16 UTC
Can't load any playermodel when SwiftAC is on (anticheat)
https://www.gmodstore.com/market/view/swiftac-clientside-anticheat-against-lua-cheats

I already told the owner here is what he told me (screenshot)
![ley](https://user-images.githubusercontent.com/1678793/71487591-990a3600-281c-11ea-9935-9fdfe8b9e956.png)

**Comment by h3xcat** [comment] 2019-12-29 00:52
How are the devs going to figure out what's breaking the addon if we have no access to his code? 

Often anti-cheats will detour core functions of gmod, breaking some functionality alongside if not done correctly, and I suspect it's most likely what happened here. I doubt any of the outfitter devs are going to get out of their way to debug and fix for commercial scripts.

Unless the issue can be reproduced with other scripts, it's up to Leystryku to fix this.

**Comment by poluxtobee** [comment] 2019-12-30 11:30
Ok, I'm fixing that alone then

**Comment by Leystryku** [comment] 2019-12-30 12:49
I don't mind giving metastruct devs who're interested in finding the cause of the issue access.  @h3xcat  @Python1320

**Comment by m4tsa** [comment] 2019-12-30 13:58
> I don't mind giving metastruct devs who're interested in finding the cause of the issue access. @h3xcat @Python1320

Well, unless I missed something it is SwiftAC breaking Outfitter and not Outfitter breaking SwiftAC. Why should it not be you fixing it? Since you are taking paid for a script that is most likely breaking outfitter by detouring and probably breaking the expected functionality of some functions.

**Comment by Leystryku** [comment] 2019-12-30 16:24
@m4tsa If I knew what functionality Outfitter is relying on which doesn't work with the AC I would have fixed it already. I've taken a look at Outfitter and due to lack of knowledge someone who's responsible for this project would have, I couldn't find anything that's breaking.

**Comment by Smartjer123** [comment] 2020-01-05 01:58
@Leystryku just an idea does swift ac have a debug mode that would print out what it is blocking or no. If it did it probably would make finding it a lot easier. I like outfitter and swift ac. You can still load stuff from outfitter but you have to go to single player then to the server and use it from the history. So my guess is that it is blocking it from downloading off the internet.

**Comment by Leystryku** [comment] 2020-01-05 04:41
As far as I know other addons which stream stuff work fine
The AC by default blocks no behaviour, infact, if it does block anything then that results in a ban. The user is however not receiving one

**Comment by Smartjer123** [comment] 2020-01-05 04:50
Maybe the anticheat and outfitter are using a function or multiple functions that dont work well together. Heck it might even be an issue with the way the gmod lua engine is setup. You will probably need a bunch of people to come together to try and troubleshoot this

**Comment by SpiralP** [comment] 2020-01-05 04:53
Outfitter gives a ton of console logs when you try to wear something, and I think it has a more verbose debug option in the gui. Could someone paste some of that output in this issue or describe it better?

**Comment by Smartjer123** [comment] 2020-01-05 04:54
Also another thing about this. When you do try and equip one directly off of the workshop it prints this no log is created on the server only on the client:

[Outfitter] doRefresh	nil
[Outfitter] Bodygroup	BTN	Refresh
[Outfitter] Bodygroup	BTN	Refresh
[Outfitter] Bodygroup	BTN	Refresh

**Comment by SpiralP** [comment] 2020-01-05 04:57
Did you try with the debug option turned on? I'm not sure the option even does anything but :p
Also outfitter uses coroutines which have a habit of swallowing errors, so maybe in one of the _G.resource function callbacks it errors

**Comment by Smartjer123** [comment] 2020-01-05 04:57
Yeah debug is on

**Comment by SpiralP** [comment] 2020-01-05 05:10
Here's the code where that last log message comes from

https://github.com/Metastruct/outfitter/blob/e6eb44897233f822aa6100b9bfe615296da4388a/lua/outfitter/gui.lua#L504-L508

it even has a silly comment talking about unhandled errors :v

outfitter does a lot of weird behavior which may be getting blocked? Some things like
```
game.MountGMA
steamworks.Download
file.Exists(..., 'workshop')
file.Exists( 'cache/workshop/' .. result.previewid .. '.cache', "GAME" )
```

Also, this addon includes code from a lot of others which are hidden around here
https://github.com/Metastruct/glua_utilities/tree/helpers/lua/includes/modules

**Comment by Smartjer123** [comment] 2020-01-16 21:38
Have to guys tried looking at the client side code because this issue is client side I believe because if the outfit was already downloaded to your client on another server it gets loaded perfectly fine. Just doesnt let you download it on that server

**Comment by Smartjer123** [comment] 2020-02-09 02:59
So is there any fix to this or is the only way to get rid of swiftac ?

**Comment by m4tsa** [comment] 2020-02-09 08:35
> So is there any fix to this or is the only way to get rid of swiftac ?

Unless ley fixes it, it is only way.

**Comment by Smartjer123** [comment] 2020-02-20 23:14
Lol I cant believe how I spend $20 on this crap ... False bans and breaks other things

**Comment by poluxtobee** [comment] 2020-04-10 14:51
SOoooo ? Anybody during outbreak ?

**Comment by Python1320** [comment] 2020-11-04 23:54
I do not have access to swiftac. Please provide logs from console with outfitter_dbg set to 10

**Comment by DarkShoot06** [comment] 2020-12-09 21:48
With outfitter_dbg 1 (i don't know why 10, but no change) and having SwiftAC on the server.
When i try to get a playermodel:

`
[HTML] https://community.cloudflare.steamstatic.com/public/javascript/j...:2: Uncaught Error: Syntax error, unrecognized expression: [data-dropdown-html

[HTML] https://community.cloudflare.steamstatic.com/public/javascript/a...:25: Uncaught TypeError: Property 'error' of object #<error> is not a function

[HTML] https://community.cloudflare.steamstatic.com/public/javascript/a...:1: Uncaught ReferenceError: LocalizationManifestReady is not defined

[HTML] https://community.cloudflare.steamstatic.com/public/javascript/g...:1542: Uncaught ReferenceError: URLSearchParams is not defined
`

Hope you could find where is the problem .

**Comment by Python1320** [comment] 2020-12-09 22:19
These are not relevant to the problem, there should be outfitter prefixed messages.

**Comment by DarkShoot06** [comment] 2020-12-09 22:21
well, nothing that can help in this case.

**Comment by Python1320** [comment] 2020-12-14 17:50
I mean you haven't captured any messages/errors from outfitter itself.

**Comment by DarkShoot06** [comment] 2020-12-14 17:54
During the process, no error appeared.
I also tried other method, like entering the id (or url) of the playermodel in the chat with a command.
No success.

**Comment by timothybvf** [comment] 2021-01-04 05:47
seems like you can't download new models but models in your history work just fine, real bummer that swiftac is doing this since outfitter is a really nice addon 😞

**Comment by Cynosphere** [comment] 2021-01-04 06:12
If theres just going to continue to be needless bumping without any help towards solving the issue properly, lets nust leave it at this then:

Pick one or the other. In my opinion and experience, anticheats are completely pointless and just more of.a headache to manage on the server end then it would be to just have proper moderation and tools to sus out potential skids as possible as can be. Especially if you run a sandbox server, there is no need to have an anticheat honestly.

Is it really worth causing more headaches towards developers that don't really need it when you inevitably know some skid is going to bypass the anticheat you wasted money on thats iust breaking more than it fixes?

Just some food for thought, take it as you will.

**Comment by m4tsa** [comment] 2021-01-04 10:35
Just going to close this, since ultimately it is SwiftAC breaking Outfitter as it is the only way to reproduce this. Since SwiftAC is a commercial product and you are entitled to support please take it up with the author and not us. If the author does not budge you can attempt to get a refund on the basis that the product is broken.

**Closed by m4tsa** 2021-01-04 10:35 UTC
